/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.logic.Game;

import org.example.logic.Board;
import org.example.ui.SwingGameWindow;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Board playerBoard = new Board();
        Board computerBoard = new Board();

        playerBoard.placeAllShipsRandomly();
        computerBoard.placeAllShipsRandomly();

        javax.swing.SwingUtilities.invokeLater(() -> {
            new SwingGameWindow(playerBoard, computerBoard);
        });
    }
}
