/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.formdev.flatlaf.FlatLightLaf;

import org.example.ui.ATMFrame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            // Set FlatLaf theme
            FlatLightLaf.setup();

            FlatLightLaf.setGlobalExtraDefaults(java.util.Map.of(
                "@font", "Ubuntu Mono-BOLD-18"
            ));
        } catch (Exception e) {
            System.err.println("Failed to initialize LaF or font");
        }

        javax.swing.SwingUtilities.invokeLater(() -> {
            ATMFrame frame = new ATMFrame();
            frame.setVisible(true);
        });
    }
}
